###############################################################
# ReadTheDocs Configuration                                   #
# (.readthedocs.yml)                                          #
# See: https://docs.readthedocs.io/en/latest/yaml-config.html #
# Adapted from https://github.com/pybel/pybel.git             #
###############################################################

python:
  version: 3
  pip_install: true
  extra_requirements:
    - docs
